
package webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AutoshowService", targetNamespace = "http://webservice/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AutoshowService {


    /**
     * 
     * @param carId
     * @return
     *     returns webservice.CarDomain
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCarById", targetNamespace = "http://webservice/", className = "webservice.GetCarById")
    @ResponseWrapper(localName = "getCarByIdResponse", targetNamespace = "http://webservice/", className = "webservice.GetCarByIdResponse")
    @Action(input = "http://webservice/AutoshowService/getCarByIdRequest", output = "http://webservice/AutoshowService/getCarByIdResponse")
    public CarDomain getCarById(
        @WebParam(name = "carId", targetNamespace = "")
        long carId);

    /**
     * 
     * @param modelName
     * @param modificationName
     * @param markName
     * @return
     *     returns webservice.CarDomain
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addCar", targetNamespace = "http://webservice/", className = "webservice.AddCar")
    @ResponseWrapper(localName = "addCarResponse", targetNamespace = "http://webservice/", className = "webservice.AddCarResponse")
    @Action(input = "http://webservice/AutoshowService/addCarRequest", output = "http://webservice/AutoshowService/addCarResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://webservice/AutoshowService/addCar/Fault/Exception")
    })
    public CarDomain addCar(
        @WebParam(name = "markName", targetNamespace = "")
        String markName,
        @WebParam(name = "modelName", targetNamespace = "")
        String modelName,
        @WebParam(name = "modificationName", targetNamespace = "")
        String modificationName)
        throws Exception_Exception
    ;

    /**
     * 
     * @param modelName
     * @param modificationName
     * @param markName
     * @throws Exception_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "removeCar", targetNamespace = "http://webservice/", className = "webservice.RemoveCar")
    @ResponseWrapper(localName = "removeCarResponse", targetNamespace = "http://webservice/", className = "webservice.RemoveCarResponse")
    @Action(input = "http://webservice/AutoshowService/removeCarRequest", output = "http://webservice/AutoshowService/removeCarResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://webservice/AutoshowService/removeCar/Fault/Exception")
    })
    public void removeCar(
        @WebParam(name = "markName", targetNamespace = "")
        String markName,
        @WebParam(name = "modelName", targetNamespace = "")
        String modelName,
        @WebParam(name = "modificationName", targetNamespace = "")
        String modificationName)
        throws Exception_Exception
    ;

    /**
     * 
     * @param modelName
     * @param modificationName
     * @param markName
     * @return
     *     returns webservice.CarDomain
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findOneCar", targetNamespace = "http://webservice/", className = "webservice.FindOneCar")
    @ResponseWrapper(localName = "findOneCarResponse", targetNamespace = "http://webservice/", className = "webservice.FindOneCarResponse")
    @Action(input = "http://webservice/AutoshowService/findOneCarRequest", output = "http://webservice/AutoshowService/findOneCarResponse")
    public CarDomain findOneCar(
        @WebParam(name = "markName", targetNamespace = "")
        String markName,
        @WebParam(name = "modelName", targetNamespace = "")
        String modelName,
        @WebParam(name = "modificationName", targetNamespace = "")
        String modificationName);

    /**
     * 
     * @param car
     * @return
     *     returns webservice.StoreDomain
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStore", targetNamespace = "http://webservice/", className = "webservice.GetStore")
    @ResponseWrapper(localName = "getStoreResponse", targetNamespace = "http://webservice/", className = "webservice.GetStoreResponse")
    @Action(input = "http://webservice/AutoshowService/getStoreRequest", output = "http://webservice/AutoshowService/getStoreResponse")
    public StoreDomain getStore(
        @WebParam(name = "car", targetNamespace = "")
        CarDomain car);

    /**
     * 
     * @param series
     * @param number
     * @return
     *     returns webservice.CustomerDomain
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findCustomerByPassport", targetNamespace = "http://webservice/", className = "webservice.FindCustomerByPassport")
    @ResponseWrapper(localName = "findCustomerByPassportResponse", targetNamespace = "http://webservice/", className = "webservice.FindCustomerByPassportResponse")
    @Action(input = "http://webservice/AutoshowService/findCustomerByPassportRequest", output = "http://webservice/AutoshowService/findCustomerByPassportResponse")
    public CustomerDomain findCustomerByPassport(
        @WebParam(name = "series", targetNamespace = "")
        String series,
        @WebParam(name = "number", targetNamespace = "")
        String number);

    /**
     * 
     * @param car
     * @param merchant
     * @param customer
     * @return
     *     returns webservice.SalesDomain
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "newSaleAndUpdateStore", targetNamespace = "http://webservice/", className = "webservice.NewSaleAndUpdateStore")
    @ResponseWrapper(localName = "newSaleAndUpdateStoreResponse", targetNamespace = "http://webservice/", className = "webservice.NewSaleAndUpdateStoreResponse")
    @Action(input = "http://webservice/AutoshowService/newSaleAndUpdateStoreRequest", output = "http://webservice/AutoshowService/newSaleAndUpdateStoreResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://webservice/AutoshowService/newSaleAndUpdateStore/Fault/Exception")
    })
    public SalesDomain newSaleAndUpdateStore(
        @WebParam(name = "customer", targetNamespace = "")
        CustomerDomain customer,
        @WebParam(name = "merchant", targetNamespace = "")
        MerchantDomain merchant,
        @WebParam(name = "car", targetNamespace = "")
        CarDomain car)
        throws Exception_Exception
    ;

    /**
     * 
     * @param merchantId
     * @return
     *     returns webservice.MerchantDomain
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMerchantById", targetNamespace = "http://webservice/", className = "webservice.GetMerchantById")
    @ResponseWrapper(localName = "getMerchantByIdResponse", targetNamespace = "http://webservice/", className = "webservice.GetMerchantByIdResponse")
    @Action(input = "http://webservice/AutoshowService/getMerchantByIdRequest", output = "http://webservice/AutoshowService/getMerchantByIdResponse")
    public MerchantDomain getMerchantById(
        @WebParam(name = "merchantId", targetNamespace = "")
        int merchantId);

}
