
package webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AutoshowServiceService", targetNamespace = "http://webservice/", wsdlLocation = "http://localhost:8889/ws/autoshow?wsdl")
public class AutoshowServiceService
    extends Service
{

    private final static URL AUTOSHOWSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException AUTOSHOWSERVICESERVICE_EXCEPTION;
    private final static QName AUTOSHOWSERVICESERVICE_QNAME = new QName("http://webservice/", "AutoshowServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8889/ws/autoshow?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AUTOSHOWSERVICESERVICE_WSDL_LOCATION = url;
        AUTOSHOWSERVICESERVICE_EXCEPTION = e;
    }

    public AutoshowServiceService() {
        super(__getWsdlLocation(), AUTOSHOWSERVICESERVICE_QNAME);
    }

    public AutoshowServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), AUTOSHOWSERVICESERVICE_QNAME, features);
    }

    public AutoshowServiceService(URL wsdlLocation) {
        super(wsdlLocation, AUTOSHOWSERVICESERVICE_QNAME);
    }

    public AutoshowServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AUTOSHOWSERVICESERVICE_QNAME, features);
    }

    public AutoshowServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AutoshowServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ShowService
     */
    @WebEndpoint(name = "AutoshowServicePort")
    public ShowService getAutoshowServicePort() {
        return super.getPort(new QName("http://webservice/", "AutoshowServicePort"), ShowService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ShowService
     */
    @WebEndpoint(name = "AutoshowServicePort")
    public ShowService getAutoshowServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice/", "AutoshowServicePort"), ShowService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AUTOSHOWSERVICESERVICE_EXCEPTION!= null) {
            throw AUTOSHOWSERVICESERVICE_EXCEPTION;
        }
        return AUTOSHOWSERVICESERVICE_WSDL_LOCATION;
    }

}
